id: P889787EA
initial_creation_type: ocr
source_metadata:
  volumes:
    926a3fe94cf84e4ea018a37786942621:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: སྙིང་པོ་ངེས་པར་བསྡུ་བ།
      total_pages: 1902
      volume_number: 64
